/**
	@file
	chroma.fromcentroid.c
	
	@name 
	cage.chroma.fromcentroid
	
	@realname 
	cage.chroma.fromcentroid

	@type
	abstraction
	
	@module
	cage

	@author
	cageproject
	
	@digest 
	Find a chroma vector corresponding having a given tonal centroid
	
	@description
	Partially reverse the tonal centroid transform by retrieving
	a chroma vector with an assigned tonal centroid.

	@discussion
	The reverse transform is not unique, since information is lost
	in the transform. One of the possible vectors is given at output. <br />
	The tonal centroid transform is computed in a similar way as
	Harte and Sandler do in 
	http://www.ofai.at/~martin.gasser/papers/oefai-tr-2006-13.pdf
	Essentially, the chroma vector is projected into three spaces: 
	one generated by fifths, one generated by minor thirds, 
	and one generated by major thirds. <br />
	@copy BACH_DOC_CHROMA
	@copy BACH_DOC_SETTHEORY_PC_AND_PCSET
	
	@category
	cage, cage set theory

	@keywords
	chroma, centroid, convert, vector, transform

	@seealso
	cage.chroma.2centroid
	
	@owner
	Daniele Ghisi
*/

// ---------------
// METHODS
// ---------------

// @method llll @digest Set tonal centroid, output result
// @description An <m>llll</m> in the first inlet is expected to be the tonal centroid
// whose original chroma should be retrieved. The conversion is not unique: 
// just one instance of the possible chroma vectors yielding the given tonal centroid
// is output. <br />
// An <m>llll</m> in the second inlet is converted into a <m>list</m>, setting the 
// projection radii (see <m>list</m>). <br /> <br />
// @copy BACH_DOC_CHROMA_TONAL_TRANSFORM
// @copy BACH_DOC_CHROMA
// @copy BACH_DOC_SETTHEORY_PC_AND_PCSET


// @method list @digest Set projection radii
// @description A <m>list</m> in the right inlet should contain three floats,
// corresponding to the three projections radii (see <m>llll</m> method), respectively 
// for: fifths, minor thirds and major thirds. Default is 1, for each space. 
// A common choice is also setting 0.5 just for minor thirds.


// @method bang @digest Output result
// @description Output the result obtained from the most recently received input data.



// ---------------
// ATTRIBUTES
// ---------------

void main_foo() {

llllobj_class_add_out_attr(c, LLLL_OBJ_VANILLA);

}

// ---------------
// INLETS
// ---------------

// @in 0 @type llll @digest The tonal centroid
// @description @copy BACH_DOC_CHROMA_TONAL_TRANSFORM
// @copy BACH_DOC_CHROMA
// @copy BACH_DOC_SETTHEORY_PC_AND_PCSET



// ---------------
// OUTLETS
// ---------------

// @out 0 @type llll @digest The chroma vector
// @description  @copy BACH_DOC_CHROMA
// @copy BACH_DOC_SETTHEORY_PC_AND_PCSET



// ---------------
// ARGUMENTS
// ---------------

// @arg 0 @name projection_radii @optional 1 @type list @digest Projection radii  
// @description Sets the initial projection radii (see <m>list</m> method). Default is <b>1 1 1</b>.